/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 腱鞘炎の人 (https://sketchfab.com/Kensyouen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/just-a-girl-b2359160a4f54e76b5ae427a55d9594d
title: Just a girl
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/justagirl.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/justagirl.gltf')
