import { Suspense } from "react";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { MeshDistortMaterial, OrbitControls } from "@react-three/drei";
// import justaGirl from "../components/Justagirl";
import IphoneModel from "../components/Iphone";
import JustagirlMoel from "../components/Justagirl";

const Home = () => {
  const Earth = () => {
    return (
      <mesh position={[0, 0, 0]} scale={2}>
        <sphereGeometry attach="geometry" args={[1, 30, 30]} />
        <MeshDistortMaterial
          attach="material"
          color="#000354"
          speed={2}
          distort={0.5}
        />
        <OrbitControls enableZoom={false} />
      </mesh>
    );
  };
  const JustAGirl = () => {
    return (
      <mesh position={[0, -1, 0]} scale={0.03}>
        <JustagirlMoel />
        <OrbitControls enableZoom={false} />
      </mesh>
    );
  };
  const IPhone = () => {
    return (
      <mesh position={[0, 0, 0]} scale={2} rotation={[0, 5, 0]}>
        <IphoneModel />
        <OrbitControls enableZoom={false} />
      </mesh>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>THREE JS</h1>
        <div className={styles.canvas}>
          <Canvas>
            <Suspense fallback={null}>
              <JustAGirl />
            </Suspense>
            <ambientLight />
            <pointLight position={[1, 1, 5]} intensity={2} />
          </Canvas>
        </div>
        <div className={styles.canvas}>
          <Canvas>
            <Suspense fallback={null}>
              <IPhone />
            </Suspense>
            <ambientLight />
            <pointLight position={[1, 1, 5]} intensity={2} />
          </Canvas>
        </div>
        <div className={styles.canvas}>
          <Canvas>
            <Suspense fallback={null}>
              <Earth />
            </Suspense>
            <ambientLight />
            <pointLight position={[1, 1, 5]} intensity={2} />
          </Canvas>
        </div>
      </main>
    </div>
  );
};

export default Home;
